version: "3"
services:
  crm:
    image: ipolotsky/israelway-crm
    platform: linux/amd64
    labels:
      autoheal: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./iway-crm.log:/opt/iway-crm.log"
    ports:
      - "5000:5000"
    env_file:
      - .env
    healthcheck:
      test: curl -sS http://127.0.0.1:5000?check=health || exit 1
      interval: 30s
      timeout: 10s
    restart: unless-stopped