version: "3"
services:
  crm:
    image: ipolotsky/israelway-crm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./iway-crm.log:/opt/iway-crm.log"
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped